slam_toolbox:
  ros__parameters:

    mode: localization

    map_file_name: "/home/pg/ros2_ws/maps/my_map3.yaml"

    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan

    use_odometry: true
    publish_tf: true

    resolution: 0.05
    max_laser_range: 12.0
